/*
 * main2.c
 *
 *  Created on: Nov 20, 2022
 *      Author: andre
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uartHandler_t huart2;

uint8_t dataReceived = 0;


int main(void)
{

	huart2.uart_Istance = UART_2;

	uint32_t delayTimeStamp = Get_SystemTimeMs();

	char *dataBuffTx = "Write something:\n\r";

	char newLine[3] = {'\n', '\r'};

	// System configurations
	System_Config();

	// Uart configuration
	uart_Init_It(&huart2);

	while(1)
	{

		if(Compare_SystemTimeMs(delayTimeStamp) > 5000)
		{

			// Write something

			uart_Start_Tx_It(&huart2, (uint8_t *)dataBuffTx, 18);

			// Wait a response

			uint8_t c = 0;

			do
			{

				// Read byte by byte what the user write

				uart_Start_Rx_It(&huart2, &c, 1);

				// Wait data received

				while(!dataReceived);

				dataReceived = 0;

				// Echo byte by byte back

				uart_Start_Tx_It(&huart2, &c, 1);

				// Increment index

			}while(c != '\r'); // Check for the end


			// Small delay between uart tx command
			delayTimeStamp = Get_SystemTimeMs();
			while(Compare_SystemTimeMs(delayTimeStamp) < 10);

			// Send a new line character

			uart_Start_Tx_It(&huart2, (uint8_t *)newLine, 2);

			// Wait 5 seconds

			delayTimeStamp = Get_SystemTimeMs();

		}

	}

}



void SysTick_CallBack(void)
{

	SysTickCountMs++;

}

void USART_ApplicationEventCallback(uartHandler_t *huart, uint8_t event)
{

	if(event == USART_EVENT_RX_CMPLT)
	{

		// Reception complete

		dataReceived = 1;

	}

}

